-- Lag tabellen brukere
CREATE TABLE brukere(
    id SERIAL PRIMARY KEY,
    fornavn VARCHAR(50),
    etternavn VARCHAR(50),
    epost VARCHAR(50),
    brukernavn TEXT,
    passord VARCHAR(20),
    fodselsdato DATE,
    avdeling TEXT,
    eradmin BOOLEAN
);

-- CHATGPT prompt: 
-- Lag 100 brukere fordelt på 6 ulike avdelinger. La selskapet være et IT-selskap. La 12 av brukerne være admin brukere. Gi meg den komplette sql-koden som setter inn dataene basert på denne tabellen: (Lim inn create table her)
CREATE TABLE brukere(
    id SERIAL PRIMARY KEY,
    fornavn VARCHAR(50),
    etternavn VARCHAR(50),
    epost VARCHAR(50),
    brukernavn TEXT,
    passord VARCHAR(20),
    fodselsdato DATE,
    avdeling TEXT,
    eradmin BOOLEAN
);

-- Sett inn 100 brukere (12 admin)
INSERT INTO brukere (fornavn, etternavn, epost, brukernavn, passord, fodselsdato, avdeling, eradmin)
VALUES
-- Avdeling 1: Utvikling (Development)
('Lars', 'Hansen', 'lars.hansen@itek.no', 'lars.hansen', 'pass123', '1985-03-12', 'Utvikling', TRUE),
('Mina', 'Johansen', 'mina.johansen@itek.no', 'mina.j', 'pass123', '1990-07-22', 'Utvikling', TRUE),
('Erik', 'Pettersen', 'erik.pettersen@itek.no', 'erik.p', 'pass123', '1988-11-05', 'Utvikling', FALSE),
('Sofie', 'Larsen', 'sofie.larsen@itek.no', 'sofie.l', 'pass125', '1992-01-18', 'Utvikling', FALSE),
('Jonas', 'Andersen', 'jonas.andersen@itek.no', 'jonas.a', 'pass126', '1987-09-30', 'Utvikling', FALSE),
('Thea', 'Bakken', 'thea.bakken@itek.no', 'thea.b', 'pass127', '1993-04-14', 'Utvikling', FALSE),
('Magnus', 'Nilsen', 'magnus.nilsen@itek.no', 'magnus.n', 'pass128', '1984-12-03', 'Utvikling', FALSE),
('Ida', 'Kristiansen', 'ida.kristiansen@itek.no', 'ida.k', 'pass129', '1991-06-27', 'Utvikling', FALSE),
('Andreas', 'Solberg', 'andreas.solberg@itek.no', 'andreas.s', 'pass130', '1989-08-19', 'Utvikling', FALSE),
('Julie', 'Henriksen', 'julie.henriksen@itek.no', 'julie.h', 'pass131', '1994-02-11', 'Utvikling', FALSE),
('Kristian', 'Moen', 'kristian.moen@itek.no', 'kristian.m', 'pass132', '1986-10-25', 'Utvikling', FALSE),
('Emma', 'Dahl', 'emma.dahl@itek.no', 'emma.d', 'pass133', '1995-05-07', 'Utvikling', FALSE),
('Martin', 'Lund', 'martin.lund@itek.no', 'martin.l', 'pass134', '1983-07-16', 'Utvikling', FALSE),
('Nora', 'Berg', 'nora.berg@itek.no', 'nora.b', 'pass135', '1996-11-22', 'Utvikling', FALSE),
('Thomas', 'Rasmussen', 'thomas.rasmussen@itek.no', 'thomas.r', 'pass136', '1988-03-09', 'Utvikling', FALSE),
('Sara', 'Jacobsen', 'sara.jacobsen@itek.no', 'sara.j', 'pass137', '1990-12-14', 'Utvikling', FALSE),
('Ole', 'Fjeld', 'ole.fjeld@itek.no', 'ole.f', 'pass138', '1987-01-30', 'Utvikling', FALSE),
('Live', 'Sørensen', 'live.sorensen@itek.no', 'live.s', 'pass139', '1993-08-04', 'Utvikling', FALSE),

-- Avdeling 2: IT-Drift (Operations / DevOps)
('Kari', 'Olsen', 'kari.olsen@itek.no', 'kari.o', 'pass201', '1982-05-17', 'IT-Drift', TRUE),
('Per', 'Vik', 'per.vik@itek.no', 'per.v', 'pass202', '1989-09-12', 'IT-Drift', TRUE),
('Line', 'Berge', 'line.berge@itek.no', 'line.b', 'pass203', '1991-03-28', 'IT-Drift', FALSE),
('Sindre', 'Haugen', 'sindre.haugen@itek.no', 'sindre.h', 'pass204', '1986-11-02', 'IT-Drift', FALSE),
('Marte', 'Lie', 'marte.lie@itek.no', 'marte.l', 'pass205', '1994-07-19', 'IT-Drift', FALSE),
('Fredrik', 'Aas', 'fredrik.aas@itek.no', 'fredrik.a', 'pass206', '1985-02-14', 'IT-Drift', FALSE),
('Ingrid', 'Myhre', 'ingrid.myhre@itek.no', 'ingrid.m', 'pass207', '1990-10-08', 'IT-Drift', FALSE),
('Vegard', 'Torp', 'vegard.torp@itek.no', 'vegard.t', 'pass208', '1988-12-21', 'IT-Drift', FALSE),
('Camilla', 'Eriksen', 'camilla.eriksen@itek.no', 'camilla.e', 'pass209', '1992-06-05', 'IT-Drift', FALSE),
('Daniel', 'Svendsen', 'daniel.svendsen@itek.no', 'daniel.s', 'pass210', '1987-04-17', 'IT-Drift', FALSE),
('Hanna', 'Steen', 'hanna.steen@itek.no', 'hanna.s', 'pass211', '1995-01-29', 'IT-Drift', FALSE),
('Jon', 'Rønning', 'jon.ronning@itek.no', 'jon.r', 'pass212', '1984-08-13', 'IT-Drift', FALSE),
('Tine', 'Nordby', 'tine.nordby@itek.no', 'tine.n', 'pass213', '1993-09-25', 'IT-Drift', FALSE),
('Marius', 'Gundersen', 'marius.gundersen@itek.no', 'marius.g', 'pass214', '1989-05-11', 'IT-Drift', FALSE),
('Elise', 'Fossum', 'elise.fossum@itek.no', 'elise.f', 'pass215', '1991-12-03', 'IT-Drift', FALSE),
('Aleksander', 'Dyrnes', 'aleksander.dyrnes@itek.no', 'aleksander.d', 'pass216', '1986-07-22', 'IT-Drift', FALSE),

-- Avdeling 3: Cybersecurity
('Anja', 'Sæther', 'anja.saether@itek.no', 'anja.s', 'pass301', '1988-02-19', 'Cybersecurity', TRUE),
('Tor', 'Løvås', 'tor.lovass@itek.no', 'tor.l', 'pass302', '1985-10-07', 'Cybersecurity', TRUE),
('Silje', 'Nilsen', 'silje.nilsen@itek.no', 'silje.n', 'pass303', '1992-04-30', 'Cybersecurity', FALSE),
('Mats', 'Brekke', 'mats.brekke@itek.no', 'mats.b', 'pass304', '1987-11-15', 'Cybersecurity', FALSE),
('Linn', 'Haug', 'linn.haug@itek.no', 'linn.h', 'pass305', '1990-08-22', 'Cybersecurity', FALSE),
('Emil', 'Røed', 'emil.roed@itek.no', 'emil.r', 'pass306', '1989-01-09', 'Cybersecurity', FALSE),
('Tuva', 'Sandvik', 'tuva.sandvik@itek.no', 'tuva.s', 'pass307', '1994-03-18', 'Cybersecurity', FALSE),
('Nikolai', 'Holm', 'nikolai.holm@itek.no', 'nikolai.h', 'pass308', '1986-06-27', 'Cybersecurity', FALSE),
('Astrid', 'Lien', 'astrid.lien@itek.no', 'astrid.l', 'pass309', '1991-09-04', 'Cybersecurity', FALSE),
('Bendik', 'Tveit', 'bendik.tveit@itek.no', 'bendik.t', 'pass310', '1988-12-12', 'Cybersecurity', FALSE),
('Helene', 'Maurstad', 'helene.maurstad@itek.no', 'helene.m', 'pass311', '1993-05-21', 'Cybersecurity', FALSE),
('Stian', 'Bjørnstad', 'stian.bjornstad@itek.no', 'stian.b', 'pass312', '1985-07-30', 'Cybersecurity', FALSE),
('Malin', 'Vik', 'malin.vik@itek.no', 'malin.v', 'pass313', '1992-02-14', 'Cybersecurity', FALSE),
('Henrik', 'Kvamme', 'henrik.kvamme@itek.no', 'henrik.k', 'pass314', '1987-10-08', 'Cybersecurity', FALSE),
('Sandra', 'Eriksen', 'sandra.eriksen@itek.no', 'sandra.e', 'pass315', '1990-11-25', 'Cybersecurity', FALSE),
('Ludvig', 'Solli', 'ludvig.solli@itek.no', 'ludvig.s', 'pass316', '1989-03-17', 'Cybersecurity', FALSE),

-- Avdeling 4: Support (Kundestøtte)
('Cecilie', 'Nygård', 'cecilie.nygaard@itek.no', 'cecilie.n', 'pass401', '1993-06-11', 'Support', TRUE),
('Even', 'Bergersen', 'even.bergersen@itek.no', 'even.b', 'pass402', '1986-09-29', 'Support', TRUE),
('Mia', 'Johnsen', 'mia.johnsen@itek.no', 'mia.j', 'pass403', '1991-01-05', 'Support', FALSE),
('David', 'Rønne', 'david.ronne@itek.no', 'david.r', 'pass404', '1988-04-22', 'Support', FALSE),
('Jenny', 'Bakke', 'jenny.bakke@itek.no', 'jenny.b', 'pass405', '1995-08-14', 'Support', FALSE),
('Sebastian', 'Midtgaard', 'sebastian.midtgaard@itek.no', 'sebastian.m', 'pass406', '1987-12-03', 'Support', FALSE),
('Karoline', 'Strand', 'karoline.strand@itek.no', 'karoline.s', 'pass407', '1992-10-19', 'Support', FALSE),
('Mathias', 'Lundberg', 'mathias.lundberg@itek.no', 'mathias.l', 'pass408', '1989-07-07', 'Support', FALSE),
('Victoria', 'Hagen', 'victoria.hagen@itek.no', 'victoria.h', 'pass409', '1994-05-26', 'Support', FALSE),
('Adrian', 'Foss', 'adrian.foss@itek.no', 'adrian.f', 'pass410', '1986-03-13', 'Support', FALSE),
('Sofia', 'Rye', 'sofia.rye@itek.no', 'sofia.r', 'pass411', '1990-02-09', 'Support', FALSE),
('Jonatan', 'Dahl', 'jonatan.dahl@itek.no', 'jonatan.d', 'pass412', '1988-11-30', 'Support', FALSE),
('Amalie', 'Hjort', 'amalie.hjort@itek.no', 'amalie.h', 'pass413', '1993-09-18', 'Support', FALSE),
('Benjamin', 'Storø', 'benjamin.storo@itek.no', 'benjamin.s', 'pass414', '1987-06-24', 'Support', FALSE),
('Hedda', 'Birkeland', 'hedda.birkeland@itek.no', 'hedda.b', 'pass415', '1991-12-11', 'Support', FALSE),
('Mikkel', 'Østby', 'mikkel.ostby@itek.no', 'mikkel.o', 'pass416', '1989-08-02', 'Support', FALSE),

-- Avdeling 5: Prosjektledelse (Project Management)
('Idun', 'Moe', 'idun.moe@itek.no', 'idun.m', 'pass501', '1984-10-15', 'Prosjektledelse', TRUE),
('Oskar', 'Sæbø', 'oskar.saebø@itek.no', 'oskar.s', 'pass502', '1987-02-28', 'Prosjektledelse', TRUE),
('Linnea', 'Vestby', 'linnea.vestby@itek.no', 'linnea.v', 'pass503', '1990-07-09', 'Prosjektledelse', FALSE),
('William', 'Gulbrandsen', 'william.gulbrandsen@itek.no', 'william.g', 'pass504', '1986-11-21', 'Prosjektledelse', FALSE),
('Nina', 'Haukelid', 'nina.haukelid@itek.no', 'nina.h', 'pass505', '1992-04-03', 'Prosjektledelse', FALSE),
('Elias', 'Lundby', 'elias.lundby@itek.no', 'elias.l', 'pass506', '1989-01-17', 'Prosjektledelse', FALSE),
('Alma', 'Sørlie', 'alma.sorlie@itek.no', 'alma.s', 'pass507', '1993-06-30', 'Prosjektledelse', FALSE),
('Noah', 'Brekstad', 'noah.brekstad@itek.no', 'noah.b', 'pass508', '1988-09-12', 'Prosjektledelse', FALSE),
('Ina', 'Røed', 'ina.roed@itek.no', 'ina.r', 'pass509', '1991-03-25', 'Prosjektledelse', FALSE),
('Lukas', 'Kolstad', 'lukas.kolstad@itek.no', 'lukas.k', 'pass510', '1987-12-08', 'Prosjektledelse', FALSE),
('Eline', 'Fjell', 'eline.fjell@itek.no', 'eline.f', 'pass511', '1994-05-14', 'Prosjektledelse', FALSE),
('Theodor', 'Huseby', 'theodor.huseby@itek.no', 'theodor.h', 'pass512', '1986-08-01', 'Prosjektledelse', FALSE),
('Frida', 'Myklebust', 'frida.myklebust@itek.no', 'frida.m', 'pass513', '1990-10-19', 'Prosjektledelse', FALSE),
('Oliver', 'Skog', 'oliver.skog@itek.no', 'oliver.s', 'pass514', '1988-02-07', 'Prosjektledelse', FALSE),
('Amanda', 'Rønning', 'amanda.ronning@itek.no', 'amanda.r', 'pass515', '1992-11-23', 'Prosjektledelse', FALSE),
('Isak', 'Tangen', 'isak.tangen@itek.no', 'isak.t', 'pass516', '1989-07-16', 'Prosjektledelse', FALSE),

-- Avdeling 6: Data & AI (Analytics / Machine Learning)
('Sondre', 'Bråten', 'sondre.braten@itek.no', 'sondre.b', 'pass601', '1987-05-10', 'Data & AI', TRUE),
('Lea', 'Steen', 'lea.steen@itek.no', 'lea.s', 'pass602', '1990-09-27', 'Data & AI', TRUE),
('Markus', 'Hauge', 'markus.hauge@itek.no', 'markus.h', 'pass603', '1986-01-14', 'Data & AI', FALSE),
('Emilie', 'Bjørn', 'emilie.bjorn@itek.no', 'emilie.b', 'pass604', '1993-04-02', 'Data & AI', FALSE),
('Jonas', 'Løvås', 'jonas.lovass@itek.no', 'jonas.lo', 'pass605', '1988-08-19', 'Data & AI', FALSE),
('Mari', 'Solvang', 'mari.solvang@itek.no', 'mari.s', 'pass606', '1991-12-05', 'Data & AI', FALSE),
('Anders', 'Nordal', 'anders.nordal@itek.no', 'anders.n', 'pass607', '1985-03-22', 'Data & AI', FALSE),
('Sofie', 'Rønneberg', 'sofie.ronneberg@itek.no', 'sofie.r', 'pass608', '1992-07-11', 'Data & AI', FALSE),
('Kristoffer', 'Dahl', 'kristoffer.dahl@itek.no', 'kristoffer.d', 'pass609', '1989-10-29', 'Data & AI', FALSE),
('Tuva', 'Moen', 'tuva.moen2@itek.no', 'tuva.m2', 'pass610', '1994-02-17', 'Data & AI', FALSE),
('Håkon', 'Vik', 'hakon.vik@itek.no', 'hakon.v', 'pass611', '1987-06-08', 'Data & AI', FALSE),
('Johanne', 'Berge', 'johanne.berge@itek.no', 'johanne.b', 'pass612', '1990-11-14', 'Data & AI', FALSE),
('Marius', 'Hagen', 'marius.hagen@itek.no', 'marius.h', 'pass613', '1986-04-25', 'Data & AI', FALSE),
('Elisabeth', 'Strand', 'elisabeth.strand@itek.no', 'elisabeth.s', 'pass614', '1993-01-09', 'Data & AI', FALSE),
('Daniel', 'Foss', 'daniel.foss2@itek.no', 'daniel.f2', 'pass615', '1988-05-30', 'Data & AI', FALSE),
('Nora', 'Solberg', 'nora.solberg@itek.no', 'nora.s2', 'pass616', '1991-08-12', 'Data & AI', FALSE);
